Uploading blueprint cloudify/gcp.yaml...
 gcp.yaml |############################################################| 100.0%
Blueprint uploaded. The blueprint's id is cloudify-wordpress-blueprint-gcp
Creating new deployment from blueprint cloudify-wordpress-blueprint-gcp...
Deployment created. The deployment's id is gcp
Executing workflow `install` on deployment `gcp` [timeout=900 seconds]
Deployment environment creation is pending...
2019-08-08 15:16:03.112  CFY <gcp> Starting 'create_deployment_environment' workflow execution
2019-08-08 15:16:03.117  CFY <gcp> Installing deployment and workflow plugins
2019-08-08 15:16:03.217  CFY <gcp> Sending task 'cloudify_agent.operations.install_plugins'
2019-08-08 15:16:03.234  CFY <gcp> Task started 'cloudify_agent.operations.install_plugins'
2019-08-08 15:16:03.549  LOG <gcp> INFO: Installing plugin: gcp_plugin
2019-08-08 15:16:04.896  LOG <gcp> INFO: Using existing installation of managed plugin: e0a99ba4-54d6-4741-a773-4ec378dc8634 [package_name: cloudify-gcp-plugin, package_version: 1.4.4, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 15:16:04.896  LOG <gcp> INFO: Installing plugin: ansible
2019-08-08 15:16:05.853  LOG <gcp> INFO: Using existing installation of managed plugin: 7142c593-6e52-429a-8a71-55266c022e02 [package_name: cloudify-ansible-plugin, package_version: 2.4.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 15:16:05.854  LOG <gcp> INFO: Installing plugin: suspend
2019-08-08 15:16:07.066  LOG <gcp> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 15:16:07.067  LOG <gcp> INFO: Installing plugin: configuration
2019-08-08 15:16:07.938  LOG <gcp> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 15:16:07.938  LOG <gcp> INFO: Installing plugin: scalelist
2019-08-08 15:16:09.086  LOG <gcp> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 15:16:09.087  CFY <gcp> Task succeeded 'cloudify_agent.operations.install_plugins'
2019-08-08 15:16:09.104  CFY <gcp> Creating deployment work directory
2019-08-08 15:16:09.379  CFY <gcp> 'create_deployment_environment' workflow execution succeeded
2019-08-08 15:16:13.606  CFY <gcp> Starting 'install' workflow execution
2019-08-08 15:16:15.863  CFY <gcp> [network_d0usja] Validating node instance before creation: nothing to do
2019-08-08 15:16:16.072  CFY <gcp> [network_d0usja] Precreating node instance: nothing to do
2019-08-08 15:16:16.431  CFY <gcp> [network_d0usja] Creating node instance
2019-08-08 15:16:16.632  CFY <gcp> [network_d0usja.create] Sending task 'cloudify_gcp.compute.network.create'
2019-08-08 15:16:18.846  LOG <gcp> [network_d0usja.create] INFO: Create network network-d0usja
2019-08-08 15:16:20.076  LOG <gcp> [network_d0usja.create] ERROR: Error traceback Traceback (most recent call last):
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 262, in _decorator
    return func(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/network.py", line 196, in create
    utils.create(network)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 163, in _decorator
    return func(resource, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 170, in create
    return resource.create()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 233, in wrapper
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/gcp.py", line 34, in _decorator
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/network.py", line 64, in create
    body=self.to_dict()).execute()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 827, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 154, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/transport.py", line 153, in new_request
    credentials._refresh(orig_request_method)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/client.py", line 765, in _refresh
    self._do_refresh_request(http_request)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/client.py", line 834, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
HttpAccessTokenRefreshError: invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
 with message invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
2019-08-08 15:16:20.077  LOG <gcp> [network_d0usja.create] ERROR: Error Message invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
2019-08-08 15:16:20.776  CFY <gcp> [network_d0usja.create] Task failed 'cloudify_gcp.compute.network.create' -> invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 277, in _decorator
    raise NonRecoverableError(error.message)
NonRecoverableError: invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.

2019-08-08 15:16:21.130  CFY <gcp> 'install' workflow execution failed: RuntimeError: Workflow failed: Task failed 'cloudify_gcp.compute.network.create' -> invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
Execution of workflow install for deployment gcp failed. [error=Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 664, in _remote_workflow_child_thread
    workflow_result = self._execute_workflow_function()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 693, in _execute_workflow_function
    result = self.func(*self.args, **self.kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/workflows.py", line 31, in install
    node_instances=set(ctx.node_instances))
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 29, in install_node_instances
    processor.install()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 102, in install
    graph.execute()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks_graph.py", line 237, in execute
    raise self._error
RuntimeError: Workflow failed: Task failed 'cloudify_gcp.compute.network.create' -> invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
]
* Run 'cfy events list 2703e08c-4dd8-4dd5-90fc-6d92ee53d610' to retrieve the execution's events/logs
