Executing workflow `uninstall` on deployment `gcp` [timeout=900 seconds]
2019-08-08 15:16:56.253  CFY <gcp> Starting 'uninstall' workflow execution
2019-08-08 15:16:57.233  CFY <gcp> [config-database_q0x8xd] Validating node instance after deletion: nothing to do
2019-08-08 15:16:57.440  CFY <gcp> [firewall_v11rb2] Validating node instance after deletion: nothing to do
2019-08-08 15:16:57.524  CFY <gcp> [config-wordpress_zle3jh] Validating node instance after deletion: nothing to do
2019-08-08 15:16:57.558  CFY <gcp> [config-wordpress_zle3jh->vm-app2_9iwawf|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-08 15:16:58.603  CFY <gcp> [config-database_q0x8xd->vm-database_xzh1dv|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-08 15:16:59.806  CFY <gcp> [config-database_q0x8xd] Stop: instance already uninitialized
2019-08-08 15:16:59.976  CFY <gcp> [firewall_v11rb2] Stop: instance already uninitialized
2019-08-08 15:17:00.085  CFY <gcp> [config-wordpress_zle3jh] Stop: instance already uninitialized
2019-08-08 15:17:01.987  CFY <gcp> [config-database_q0x8xd] Delete: instance already uninitialized
2019-08-08 15:17:02.300  CFY <gcp> [firewall_v11rb2] Delete: instance already uninitialized
2019-08-08 15:17:02.532  CFY <gcp> [config-wordpress_zle3jh] Delete: instance already uninitialized
2019-08-08 15:17:02.984  CFY <gcp> [config-wordpress_zle3jh->vm-app2_9iwawf|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-08 15:17:03.214  CFY <gcp> [config-wordpress_zle3jh->vm-app1_3i7t17|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-08 15:17:03.441  CFY <gcp> [config-database_q0x8xd] Deleted node instance
2019-08-08 15:17:03.552  CFY <gcp> [firewall_v11rb2] Deleted node instance
2019-08-08 15:17:04.308  CFY <gcp> [config-wordpress_zle3jh] Deleted node instance
2019-08-08 15:17:04.485  CFY <gcp> [config-database_q0x8xd->vm-database_xzh1dv|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-08 15:17:06.128  CFY <gcp> [config-wordpress_zle3jh->vm-app1_3i7t17|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-08 15:17:06.502  CFY <gcp> [vm-app1_3i7t17] Validating node instance after deletion: nothing to do
2019-08-08 15:17:06.672  CFY <gcp> [vm-app2_9iwawf] Validating node instance after deletion: nothing to do
2019-08-08 15:17:06.962  CFY <gcp> [vm-app1_3i7t17] Stop: instance already uninitialized
2019-08-08 15:17:07.015  CFY <gcp> [vm-app2_9iwawf] Stop: instance already uninitialized
2019-08-08 15:17:07.468  CFY <gcp> [vm-app1_3i7t17] Delete: instance already uninitialized
2019-08-08 15:17:07.580  CFY <gcp> [vm-app2_9iwawf] Delete: instance already uninitialized
2019-08-08 15:17:07.806  CFY <gcp> [vm-app1_3i7t17] Deleted node instance
2019-08-08 15:17:07.867  CFY <gcp> [vm-app2_9iwawf] Deleted node instance
2019-08-08 15:17:08.423  CFY <gcp> [vm-database_xzh1dv] Validating node instance after deletion: nothing to do
2019-08-08 15:17:08.620  CFY <gcp> [vm-database_xzh1dv] Stop: instance already uninitialized
2019-08-08 15:17:08.898  CFY <gcp> [vm-database_xzh1dv] Delete: instance already uninitialized
2019-08-08 15:17:09.205  CFY <gcp> [vm-database_xzh1dv] Deleted node instance
2019-08-08 15:17:09.541  CFY <gcp> [subnet_whvl8n] Validating node instance after deletion: nothing to do
2019-08-08 15:17:09.937  CFY <gcp> [subnet_whvl8n] Stop: instance already uninitialized
2019-08-08 15:17:10.261  CFY <gcp> [subnet_whvl8n] Delete: instance already uninitialized
2019-08-08 15:17:10.620  CFY <gcp> [subnet_whvl8n] Deleted node instance
2019-08-08 15:17:11.279  CFY <gcp> [network_d0usja] Stopping node instance
2019-08-08 15:17:11.544  CFY <gcp> [network_d0usja] Validating node instance after deletion: nothing to do
2019-08-08 15:17:11.769  CFY <gcp> [network_d0usja] Stopped node instance: nothing to do
2019-08-08 15:17:12.049  CFY <gcp> [network_d0usja] Unlinking relationships
2019-08-08 15:17:12.330  CFY <gcp> [network_d0usja] Relationships unlinked
2019-08-08 15:17:12.528  CFY <gcp> [network_d0usja] Deleting node instance
2019-08-08 15:17:12.970  CFY <gcp> [network_d0usja.delete] Sending task 'cloudify_gcp.compute.network.delete'
2019-08-08 15:17:14.909  LOG <gcp> [network_d0usja.delete] INFO: Delete network network-d0usja
2019-08-08 15:17:15.533  LOG <gcp> [network_d0usja.delete] ERROR: Error traceback Traceback (most recent call last):
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 262, in _decorator
    return func(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/network.py", line 215, in delete
    utils.delete_if_not_external(network)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 175, in delete_if_not_external
    return resource.delete()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 233, in wrapper
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/gcp.py", line 34, in _decorator
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/network.py", line 80, in delete
    network=self.name).execute()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 827, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 154, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/transport.py", line 153, in new_request
    credentials._refresh(orig_request_method)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/client.py", line 765, in _refresh
    self._do_refresh_request(http_request)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/client.py", line 834, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
HttpAccessTokenRefreshError: invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
 with message invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
2019-08-08 15:17:15.533  LOG <gcp> [network_d0usja.delete] ERROR: Error Message invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
2019-08-08 15:17:16.061  CFY <gcp> [network_d0usja.delete] Task failed 'cloudify_gcp.compute.network.delete' -> invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 277, in _decorator
    raise NonRecoverableError(error.message)
NonRecoverableError: invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.

2019-08-08 15:17:16.859  CFY <gcp> [network_d0usja] Deleted node instance
2019-08-08 15:17:17.400  CFY <gcp> 'uninstall' workflow execution succeeded
Finished executing workflow uninstall on deployment gcp
* Run 'cfy events list af7b218b-b45d-4e24-a28e-f8c8c537e465' to retrieve the execution's events/logs
Trying to delete deployment gcp...
Deployment deleted
Deleting blueprint cloudify-wordpress-blueprint-gcp...
Blueprint deleted
